name: action
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
      steps:
        - run: |
            git init .
            git remote add origin "https://x-access-token:${{ github.token }}@github.com/${{ github.repository }}.git"
            git fetch --no-tags --depth=1 origin ${{ github.sha }}
            git checkout --detach ${{ github.sha }}
        - run: pipx install uv
        - run: uv sync
        - run: uv run build.py
